//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTable
    {
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBird { get; set; }
        public bool Gender { get; set; }
        public int Task { get; set; }
    }
}
