//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAct
    {
        public int id { get; set; }
        public System.DateTime dateAct { get; set; }
        public string Action { get; set; }
    }
}
